name: Deploy CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Use the appropriate Python version for your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # You can customize pytest options as needed
      continue-on-error: false  # Fail the deployment if pytest fails

    - name: Copy files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "./"
        target: "${{ secrets.TARGET_DIR }}"

    - name: Run remote commands on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          export DATABASE_URL_CREATE=${{ secrets.DATABASE_URL_CREATE }}

          cd ${{ secrets.TARGET_DIR }}
          pip3 install -r requirements.txt
          python3 create_db.py
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 &
